### ISSUE TITLE
Jubi, Jubi, BtcTrade failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [drpout/libdynticker#13]
Results :

Failed tests:   testGetPairs(mobi.boilr.libdynticker.exchanges.JubiExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.JubiExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BtcTradeExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 284, Failures: 3, Errors: 2, Skipped: 1

**Comment by dllud** [comment]
Both sites are under temporary maintenance.
