### ISSUE TITLE
CampBX, CoinsE, Coinut, Coinut, Bitcurex, ItBit failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [drpout/libdynticker#17]
Results :

Failed tests:   testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CampBXExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CoinsEExchangeTest)
  testGetPairs(mobi.boilr.libdynticker.exchanges.CoinutExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CoinutExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitcurexExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.ItBitExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 284, Failures: 6, Errors: 2, Skipped: 1

**Comment by andrefbsantos** [comment]
Coinut is under maintance.
Others are working properly.
