### ISSUE TITLE
Bitspark, Bitspark, CampBX, VirWox, VirWox, BtcTrade, Melotic failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [drpout/libdynticker#19]
Results :

Failed tests:   testGetPairs(mobi.boilr.libdynticker.exchanges.BitsparkExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitsparkExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CampBXExchangeTest)
  testGetPairs(mobi.boilr.libdynticker.exchanges.VirWoxExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.VirWoxExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BtcTradeExchangeTest)
  testGetPairs(mobi.boilr.libdynticker.exchanges.MeloticExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 284, Failures: 7, Errors: 2, Skipped: 1

**Comment by andrefbsantos** [comment]
Bitspark is in maintenance.
https://twitter.com/BitsparkBTC/status/589442448759259137
