### ISSUE TITLE
Bitspark, Bitspark, CampBX, VirWox, OneWorldCoin, OneWorldCoin, Cryptsy, : Java heap space testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker Tests run: 280, Failures: 6, Errors: 3, Skipped: 1 failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [drpout/libdynticker#24]
Results :

Failed tests:   testGetPairs(mobi.boilr.libdynticker.exchanges.BitsparkExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitsparkExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CampBXExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.VirWoxExchangeTest)
  testGetPairs(mobi.boilr.libdynticker.exchanges.OneWorldCoinExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.OneWorldCoinExchangeTest)

Tests in error: 
  testGetPairs(mobi.boilr.libdynticker.exchanges.CryptsyExchangeTest): Java heap space
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 280, Failures: 6, Errors: 3, Skipped: 1

**Comment by Blackrc** [comment]
Intresting. Im very intresting test my service, your app
