### ISSUE TITLE
Adding binance exhange integration

### ISSUE THREAD

**Issue by TorgeirCook** [drpout/libdynticker#45]
Hi,

Love Boilr, best app I have found so far giving cryptoalerts. Any plans on adding integration with the binance exchange, perhaps i could contribute?

**Comment by dllud** [comment]
Thanks! Contributions are much welcomed.

Binance seems straightforward. You can build the pairs list with [allPrices](https://www.binance.com/api/v1/ticker/allPrices) and retrieve the last price for a single pair with [24hr](https://www.binance.com/api/v1/ticker/24hr?symbol=LTCBTC).

Please take a look at our [contribution guidelines](https://github.com/drpout/libdynticker/blob/master/CONTRIBUTING.md).

**Comment by TorgeirCook** [comment]
How can I get my code merged? I don't have access to create a Pull request.

**Comment by dllud** [comment]
Pull requests are open to anyone. You can create one by forking this repo to your GitHub profile, committing your changes over there and issuing a pull request.
